#:schema node_modules/wrangler/config-schema.json
name = "talk-to-javascript"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"